<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sebuah Pesan Spesial</title>
    <style>
        /* CSS untuk keseluruhan halaman dan animasi */
        @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap');

        :root {
            --primary-color: #0d0d2b;
            --secondary-color: #2c2c54;
            --text-color: #e0e0e0;
            --accent-color: #00f6ff;
            --glow-color: rgba(0, 246, 255, 0.7);
        }

        body {
            margin: 0;
            font-family: 'Orbitron', sans-serif;
            background-color: var(--primary-color);
            color: var(--text-color);
            overflow: hidden;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            text-align: center;
        }

        .page {
            display: none; /* Semua halaman disembunyikan secara default */
            flex-direction: column;
            align-items: center;
            justify-content: center;
            width: 100%;
            max-width: 600px;
            padding: 20px;
            box-sizing: border-box;
            background: rgba(13, 13, 43, 0.8);
            border-radius: 15px;
            box-shadow: 0 0 25px var(--glow-color);
            border: 1px solid var(--accent-color);
            animation: fadeIn 1s forwards;
        }

        .page.active {
            display: flex; /* Hanya halaman aktif yang ditampilkan */
        }

        @keyframes fadeIn {
            from { opacity: 0; transform: scale(0.9); }
            to { opacity: 1; transform: scale(1); }
        }

        h1, h2 {
            text-shadow: 0 0 10px var(--glow-color);
        }

        .input-field {
            background-color: var(--secondary-color);
            border: 2px solid var(--accent-color);
            color: var(--text-color);
            padding: 15px;
            border-radius: 10px;
            margin: 20px 0;
            width: 80%;
            font-family: 'Orbitron', sans-serif;
            font-size: 1.2em;
            text-align: center;
            box-shadow: 0 0 15px var(--glow-color) inset;
        }

        .input-field::placeholder {
            color: #aaa;
        }

        .btn {
            background: var(--accent-color);
            color: var(--primary-color);
            border: none;
            padding: 15px 30px;
            font-family: 'Orbitron', sans-serif;
            font-size: 1.1em;
            font-weight: bold;
            cursor: pointer;
            border-radius: 10px;
            text-transform: uppercase;
            box-shadow: 0 0 20px var(--glow-color);
            transition: all 0.3s ease;
            margin-top: 10px;
        }

        .btn:hover {
            transform: scale(1.1);
            box-shadow: 0 0 30px var(--glow-color);
        }
        
        #blackhole-img, #space-video {
            max-width: 100%;
            height: auto;
            border-radius: 10px;
            margin-bottom: 20px;
            border: 2px solid var(--accent-color);
        }

        /* Halaman Keenam - Final */
        #final-page {
            max-width: 800px;
        }
        
        .rgb-title {
            font-size: 3em;
            font-weight: bold;
            animation: rgb-animation 5s infinite linear;
        }

        @keyframes rgb-animation {
            0% { color: #ff00de; text-shadow: 0 0 20px #ff00de; }
            25% { color: #00f6ff; text-shadow: 0 0 20px #00f6ff; }
            50% { color: #33ff00; text-shadow: 0 0 20px #33ff00; }
            75% { color: #f2ff00; text-shadow: 0 0 20px #f2ff00; }
            100% { color: #ff00de; text-shadow: 0 0 20px #ff00de; }
        }

        .space-message {
            font-size: 1.2em;
            line-height: 1.6;
            margin-top: 20px;
            max-width: 90%;
        }

        /* Animasi Latar Belakang (Bintang & Meteor) */
        .star {
            position: absolute;
            background-color: white;
            border-radius: 50%;
            box-shadow: 0 0 10px white;
            animation: twinkle linear infinite;
        }
        
        .meteor {
            position: absolute;
            width: 3px;
            height: 80px;
            background: linear-gradient(to bottom, rgba(255, 255, 255, 0.8), transparent);
            transform: rotate(-45deg);
            animation: meteor-fall linear infinite;
        }

        @keyframes twinkle {
            0%, 100% { opacity: 0.5; }
            50% { opacity: 1; }
        }
        
        @keyframes meteor-fall {
            0% { transform: translate(0, -200px) rotate(-45deg); opacity: 1; }
            100% { transform: translate(-100vw, 100vh) rotate(-45deg); opacity: 0; }
        }

    </style>
</head>
<body>

    <audio id="background-music" loop>
        <source src="hmmm.mp3" type="audio/mpeg">
        Browser Anda tidak mendukung elemen audio.
    </audio>

    <div id="page1" class="page active">
        <h2>Halo, kamu siapa?</h2>
        <input type="text" id="name" class="input-field" placeholder="Ketik nama di sini...">
        <button class="btn" onclick="checkName()">Lanjut</button>
    </div>

    <div id="page2" class="page">
        <h2>Siapa temanmu yang namanya berawalan 'F'?</h2>
        <input type="text" id="friendName" class="input-field" placeholder="Ketik namanya di sini...">
        <button class="btn" onclick="checkFriendName()">Lanjut</button>
    </div>

    <div id="page3" class="page">
        <h2>Apakah kamu yakin? Ini adalah perjalanan satu arah.</h2>
        <button class="btn" onclick="showPage('page4')">Ya, Aku Yakin!</button>
    </div>

    <div id="page4" class="page">
        <h2>Gerbang pertama telah terbuka...</h2>
        <img id="Black Holes" src="image.png" alt="Black Hole">
        <button class="btn" onclick="showPage('page5')">Lanjutkan Perjalanan</button>
    </div>

    <div id="page5" class="page">
        <h2>Menjelajahi alam semesta...</h2>
        <video id="Universe" width="560" height="315" controls autoplay muted>
            <source src="gege.mp4" type="video/mp4">
            Browser Anda tidak mendukung tag video.
        </video>
        <p style="font-size: 0.8em;">(Jika video tidak berputar otomatis, klik tombol play)</p>
        <button class="btn" onclick="goToFinalPage()">Ke Tujuan Akhir</button>
    </div>

    <div id="page6" class="page">
        <h1 class="rgb-title">By Kapten Fahmi</h1>
        <p class="space-message">
            Untuk temanku, kita seperti dua bintang dalam galaksi yang luas ini. Terkadang jauh, namun selalu berada di bawah langit yang sama. Ingatlah, bahkan lubang hitam paling gelap sekalipun tidak bisa menelan cahaya dari persahabatan kita. Teruslah bersinar, kawan! Alam semesta menantimu.
        </p>
    </div>

    <script>
        // JavaScript untuk fungsionalitas halaman (Tidak ada yang perlu diubah di sini)

        function showPage(pageId) {
            document.querySelectorAll('.page').forEach(page => {
                page.classList.remove('active');
            });
            const nextPage = document.getElementById(pageId);
            if (nextPage) {
                nextPage.classList.add('active');
            }
        }

        function checkName() {
            const nameInput = document.getElementById('name').value.trim().toLowerCase();
            if (nameInput === 'dirgham' || nameInput === 'faqih') {
                showPage('page2');
            } else {
                alert('Nama tidak dikenali. Coba lagi!');
            }
        }

        function checkFriendName() {
            const friendNameInput = document.getElementById('friendName').value.trim().toLowerCase();
            if (friendNameInput === 'fahmi') {
                showPage('page3');
            } else {
                alert("Nama teman salah. Dia yang paling keren dengan awalan 'F'!");
            }
        }
        
        function goToFinalPage() {
            showPage('page6');
            const music = document.getElementById('background-music');
            music.play().catch(error => {
                console.log("Autoplay musik dicegah oleh browser. Interaksi pengguna diperlukan.");
            });
            createStars(100);
            createMeteors(10);
        }

        function createStars(count) {
            const body = document.body;
            for (let i = 0; i < count; i++) {
                const star = document.createElement('div');
                star.classList.add('star');
                const size = Math.random() * 3 + 1;
                star.style.width = `${size}px`;
                star.style.height = `${size}px`;
                star.style.top = `${Math.random() * 100}%`;
                star.style.left = `${Math.random() * 100}%`;
                star.style.animationDuration = `${Math.random() * 3 + 2}s`;
                star.style.animationDelay = `${Math.random() * 2}s`;
                body.appendChild(star);
            }
        }
        
        function createMeteors(count) {
            const body = document.body;
            for (let i = 0; i < count; i++) {
                const meteor = document.createElement('div');
                meteor.classList.add('meteor');
                meteor.style.top = `${Math.random() * -100}px`;
                meteor.style.left = `${Math.random() * 100}%`;
                const duration = Math.random() * 5 + 5;
                meteor.style.animation = `meteor-fall ${duration}s linear infinite`;
                meteor.style.animationDelay = `${Math.random() * 10}s`;
                body.insertBefore(meteor, body.firstChild);
            }
        }
    </script>
</body>
</html>
